"""initial schema

Revision ID: 3555ccf5fcb6
Revises: 
Create Date: 2026-06-17 18:38:15.044912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3555ccf5fcb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('exam_name', sa.String(length=60), nullable=False),
    sa.Column('target_exam_date', sa.String(length=10), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('habits',
    sa.Column('habit_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('completed_dates', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('habit_id')
    )
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('timetable',
    sa.Column('entry_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('teacher', sa.String(length=120), nullable=True),
    sa.Column('start_time', sa.String(length=8), nullable=False),
    sa.Column('end_time', sa.String(length=8), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index(op.f('ix_timetable_date'), 'timetable', ['date'], unique=False)
    op.create_index('ix_timetable_user_date', 'timetable', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_timetable_user_id'), 'timetable', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('session_token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_token')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # ── RLS hardening (defense-in-depth) ───────────────────────────────
    # Backend connects as the postgres role (superuser) which BYPASSES RLS.
    # These policies block any anon/authenticated client that ever tries to
    # query the tables directly via Supabase's REST/JS clients.
    for table in ("users", "user_sessions", "habits", "timetable"):
        op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY;')
        op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY;')
        # Explicit deny-all policy for anon + authenticated; postgres bypasses
        op.execute(f"""
            CREATE POLICY "{table}_deny_all" ON "{table}"
            FOR ALL TO anon, authenticated
            USING (false) WITH CHECK (false);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for table in ("users", "user_sessions", "habits", "timetable"):
        op.execute(f'DROP POLICY IF EXISTS "{table}_deny_all" ON "{table}";')
        op.execute(f'ALTER TABLE "{table}" DISABLE ROW LEVEL SECURITY;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_timetable_user_id'), table_name='timetable')
    op.drop_index('ix_timetable_user_date', table_name='timetable')
    op.drop_index(op.f('ix_timetable_date'), table_name='timetable')
    op.drop_table('timetable')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_table('habits')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
